name: Kubernetes Client Python Test

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tox-env: [py35, py36, py37, py38, py39, nolxml, nohtml5lib]
        include:
          - tox-env: py35
            python-version: 3.5
          - tox-env: py36
            python-version: 3.6
          - tox-env: py37
            python-version: 3.7
          - tox-env: py38
            python-version: 3.8
          - tox-env: py39
            python-version: 3.9
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test with tox ${{ matrix.tox-env }}
      env: ${{ matrix.tox-env }}
      run: tox
    - name: Verify boilerplate
      run: ./hack/verify-boilerplate.sh      