name: Kubernetes Client Python Test

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.5
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions

    - name: Test with tox ${{ matrix.env }}
      env: 
        TOXENV: py35
      run: ./run_tox.sh tox
    - name: Verify boilerplate
      run: ./hack/verify-boilerplate.sh      